<?php
    Class DeliveryArea {
        var $StoreID,
        $MenuID,
        $PCode,
        $Radius,
        $Cost;

        function DeliveryArea {

        }

        function setDeliveryAreaVar($varname, $varvalue)
        {
            $this->$varname=$varvalue;
        }

        function getDeliveryArea()
        {

        }

        function createDeliveryArea()
        {

        }

        function updateDeliveryArea()
        {

        }

        function deleteDeliveryArea()
        {

        }

        function checkRadius()
        {

        }

        function checkUserInsideRadius()
        {

        }
    }
?>